// Generated by Haxe 3.4.7
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	window.addEventListener("DOMContentLoaded",function() {
		js_youtube_Youtube.init(Main.onAPIReady);
	});
};
Main.onAPIReady = function() {
	var target = window.document.getElementById("video");
	var player = new YT.Player(target.id,{ videoId : target.dataset.videoId, events : { onReady : function(event) {
	}}});
};
var js_youtube_Youtube = function() { };
js_youtube_Youtube.init = function(onAPIReady) {
	var firstElement = window.document.getElementsByTagName("script")[0];
	var script = window.document.createElement("script");
	script.src = "https://www.youtube.com/player_api";
	firstElement.parentNode.insertBefore(script,firstElement);
	window.onYouTubePlayerAPIReady = function() {
		js_youtube_Youtube.isLoadedAPI = true;
		if(onAPIReady != null) {
			onAPIReady();
		}
	};
};
js_youtube_Youtube.isLoadedAPI = false;
js_youtube_Youtube.API_URL = "https://www.youtube.com/player_api";
Main.main();
})();
